### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by kousik97** [bikz05/object-tracker#7]
After selecting the object to be tracked using mouse and pressing the key 'p', I am getting the following error in my terminal.

Press key `p` to pause the video to start tracking
init done 
opengl support available 
Press and release mouse around the object to be tracked. 
 You can also select multiple objects.
Press key `p` to continue with the selected points.
Press key `d` to discard the last object selected.
Press key `q` to quit the program.
Object selected at [(224, 166), (412, 323)]
**Illegal instruction (core dumped)**

**Comment by ghost** [comment]
Hello，I have encountered similar problems.
dlib is compiled with SSE4 or AVX support, but your CPU is too old and doesn't support that. You'll need to recompile dlib after making the code change outlined here.
The issue is most likely that dlib was compiled with support for AVX and/or SSE4 instructions, but your cpu is too old to support them .
If you want to run the example in your computer.The easiest solution is to download dlib and compile it yourself. But when you do that, you need to make one change.
Before compiling dlib, edit dlib's tools/python/CMakeLists.txt file from:
set(USE_SSE4_INSTRUCTIONS ON CACHE BOOL "Use SSE4 instructions")
to:
set(USE_SSE2_INSTRUCTIONS ON CACHE BOOL "Use SSE2 instructions")
And then compile and install dlib and the dlib python extensions. 
I used this method and the example worked.
